name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Login to Vercel
      run: npx vercel login --token ${{ secrets.VERCEL_TOKEN }}
      
    - name: Build Project
      run: yarn build

    - name: Deploy to Vercel
      run: npx vercel --prod
