name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Vercel environment
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: echo "//registry.npmjs.org/:_authToken=\${VERCEL_TOKEN}" >> ~/.npmrc

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build

    - name: Deploy to Vercel
      run: npx vercel --prod
